### ISSUE TITLE
Failed to Execute (ParametrizeLandCoverandSoils)

### ISSUE THREAD

**Issue by kennethelsner** [ARS-SWRC/agwa#6]
Good Afternoon,

I have successfully run AGWA in the State of Oregon. I am running AGWA in a new part of Oregon and I am receiving the following error during Parametrization. The same gSSURGO data and LC data worked in another part of the state. Is **texture fragmental material** in the AGWA lookup table the issue? If yes, is there a way to tweak the table to allow parameterization to complete successfully?

![image](https://github.com/user-attachments/assets/22950d4c-7883-43e9-8e5c-bd0fc23c1976)

Thanks!

**Comment by haiyan-Wei** [comment]
Thank you for bringing this to my attention. That's right, Fragmental is not in the lookup table yet. I’ll look into it as soon as possible. If you’re familiar with this texture type and comfortable tweaking the table on your end, you can edit the table kin_lut in the lookup_tables.gdb file, located in the AGWApro_v0.5_directory folder.

**Comment by haiyan-Wei** [comment]
@kennethelsner
The "Fragmental material" texture is now available in the AGWA lookup table. We've also updated the Ks and G values for the most common soil texture types based on our latest knowledge. I also fixed a bug in Step 5. 

The new code is ready to go, please test it with the updated "**AGWApro V0.5 Directory**" available here: https://www.tucson.ars.ag.gov/agwa/downloads/.

I appreciate your patience.

**Comment by kennethelsner** [comment]
At least I got a new error this time?
![image](https://github.com/user-attachments/assets/0ad9511f-9e8f-496e-a00e-6bfa7802026f)

**Comment by jburgessconforti** [comment]
![step4agwa](https://github.com/user-attachments/assets/374946ff-bf46-46f7-92fb-10e0c49ed9a3)


Since we've started this thread I've gone from having it break on step 5 to having it break on step 4...

**Comment by haiyan-Wei** [comment]
> At least I got a new error this time? ![image](https://private-user-images.githubusercontent.com/177868093/363368166-0ad9511f-9e8f-496e-a00e-6bfa7802026f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTIxODIsIm5iZiI6MTcyNTI1MTg4MiwicGF0aCI6Ii8xNzc4NjgwOTMvMzYzMzY4MTY2LTBhZDk1MTFmLTllOGYtNDk2ZS1hMDBlLTZiZmE3ODAyMDI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwNDM4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzk4YWYyMDhjZWMyNzNhYjY3ZGRmNGE1MGIzM2U4ZjViMDQ5MzM4YmViYjlhNGIzNmZkOWU2ODNhMDRmN2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k8-hJI3bDvnGZ7KZZExihEhiwHkCgPgJ3H-CABIyiCY)

@kennethelsner It looks like AGWA was looking for table **component** in folder **agwa_gwen**, which does not look like a file geodatabase. I'm curious what's your input for step 19.6? If you uncheck 19.6, an input box should show up and let you choose the file geodatabase where table component is located. Could you check if that's the right directory for table **component**?

**Comment by haiyan-Wei** [comment]
@jburgessconforti 
Thanks for sharing the error message. I think I know what has caused this error. I'm on it!

**Comment by jburgessconforti** [comment]
@haiyan-Wei So I was able to get rid of the none of dem.tif was found error message but shoving everything in to a .gdb. It looks like arc or the code wasn't working well with the periods in the file extension. I'm getting an error still on step 4 but its only about floats and none types (see below). I appreciate the quick response and all the work you're doing on this.

![step4error2](https://github.com/user-attachments/assets/0f8ff0a4-98ff-43c1-b34d-004b31d96ade)

**Comment by haiyan-Wei** [comment]
@jburgessconforti Thanks for letting me know. I'm glad you got it!
This has happened to me before. I thought I had made sure the issue with the file extension was taken care of. I'll double-check!

**Comment by kennethelsner** [comment]
@haiyan-Wei The soil database was totally my fault. Thanks for pointing it out.

I was picking up a project that I hadn't touched in few weeks and I didn't have my default soil database in the correct location. Pointing to the gSSURGO database fixed my issue in Step 5. I made it all the way to Executing the Sim which gave me the following conflicting error. CMD prompt says error while Pro says successful. That type of conflicting messaging is confusing for users. 
![image](https://github.com/user-attachments/assets/42b3d066-9746-4965-9fd3-78ffa414073a)

Not sure why the script is looking for hillslope 94 when the last hillslope in the discretization is 93. 
![image](https://github.com/user-attachments/assets/697c724c-eac8-42c8-855b-bc302ad8a33d)

**Comment by haiyan-Wei** [comment]
@kennethelsner 

I believe AGWA sets a default value for the slope of very flat channels as a small number to prevent this error. If not, we need to change that. 

I wonder if something went wrong in Step 4. Could you open the **parameters_channels** table located in the file geodatabase for your delineation and check if the other channel parameters look reasonable?

For example, in the case of the tutorial, it would be the **parameters_channels** table in **E:\agwa_prj\learn_agwa\fire_demo\AndreasCanyon\AndreasCanyon.gdb**.

Thanks!

![image](https://github.com/user-attachments/assets/64e12ed9-858e-485a-9ca5-81d6ee862656)

**Comment by kennethelsner** [comment]
@haiyan-Wei I think it is a great idea to give very flat channels a small number to prevent the error.

 It does not appear, that agwa is honoring any default value. 2 negative values in meanslope
 
![image](https://github.com/user-attachments/assets/6df63ede-8a7c-4dc5-b16e-9241aa11c840)

**Comment by haiyan-Wei** [comment]
@kennethelsner 
Thank you for your feedback. I've made the changes, along with a few minor adjustments to the interfaces of several steps.
The channel slope is calculated based on upstream and downstream elevations, which could sometimes result in a negative value for flat channels.  I’ve added a minimal threshold of 0.001. 

If you'd like to test your watershed again, please let me know if everything works as expected this time. Thanks again!

**Comment by Captina** [comment]
Well I finally made it past step but I did have to add two more textures, Highly and Moderately decomposed plant material to the Kin_lut table.

Now its failing at step five with this message:

Traceback (most recent call last):
  File "C:\AGWA\agwa-pro-toolbox_v0.5_beta\code\src\tool_parameterize_land_cover_and_soils.py", line 364, in execute
    agwa.parameterize(prjgdb, workspace, delineation, discretization, parameterization_name, save_intermediate_outputs)
  File "C:\AGWA\agwa-pro-toolbox_v0.5_beta\code\src\code_parameterize_land_cover_and_soils.py", line 68, in parameterize
    parameterize_hillslopes(workspace, delineation_name, discretization_name, parameterization_name, 
  File "C:\AGWA\agwa-pro-toolbox_v0.5_beta\code\src\code_parameterize_land_cover_and_soils.py", line 91, in parameterize_hillslopes
    df_cover = intersect_weight_land_cover_by_area(workspace, delineation_name, discretization_name, land_cover, 
  File "C:\AGWA\agwa-pro-toolbox_v0.5_beta\code\src\code_parameterize_land_cover_and_soils.py", line 217, in intersect_weight_land_cover_by_area
    apply_buffer_flag, buffer_size = is_raster_larger_and_buffer(land_cover, watershed_feature_class)
  File "C:\AGWA\agwa-pro-toolbox_v0.5_beta\code\src\code_parameterize_land_cover_and_soils.py", line 849, in is_raster_larger_and_buffer
    raise Exception(f"The raster {raster} does not cover the entire watershed. "
Exception: The raster E:\ArcGIS\Layers\nlcd_2019_land_cover_l48_20210604.img does not cover the entire watershed. Please provide a raster that covers the entire watershed.
Failed to execute (ParameterizeLandCoverAndSoils).



Despite the NLCD raster being well large enough to cover the watershed

**Comment by haiyan-Wei** [comment]
Hello Capina,

Thank you for the message, from another message threshold, it looked like
the new code worked out for you and this no longer is an issue. Let me know
if it is otherwise.

Best,
Haiyan
